### ISSUE TITLE
Improvement of ElevationMap::move_to performance

### ISSUE THREAD

**Issue by AlexReimann** [leggedrobotics/elevation_mapping_cupy#12]
Hi,
I'm running the package under ROS melodic, Ubuntu 18.04 in Simulation with a simulated Velodyne VLP-16.
I tried to lower the CPU usage to something like our current traversability estimation uses. 

I tried to lower it by following without much change:

* Remove plugins, leaving 1 disabled plugin
* Decrease `resolution` to 0.2 m
* Decrease `map_length` to 2 m
* Decrease `max_ray_length` to 1 m 
* Disable all the features via feature toggles
* Remove all publishers
* Decrease `map_acquire_fps` to 2 Hz

Profiling the with these configs showed that the `move_to` function  in `elevation_mapping.py` uses most CPU cycles (60%).
Changing the `update_pose_fps` then lowered the CPU as expected.

Are there any plans to improve the performance of this `move_to` function?

**Comment by lorenwel** [comment]
Hi Alex, 

using `ndimage.interpolate.shift` to move the map is probably overkill here. @mktk1117 is looking into it.

What is a bit weird, though is that it has impact on the CPU usage, since everything here is or should be executed on GPU. This means the mutex in that function might also be a factor.

**Comment by mktk1117** [comment]
Hi Alex,
I replaced the `ndimage.interpolate.shift` with `cp.roll` and filling in using slicing.
I pushed to the branch `fix/improve_shifting`
Could you try out this branch and let us know if this solved the issue?
Also it would be great if you could check #13 with this branch as well.

**Comment by AlexReimann** [comment]
It seems to have improved with the branch.
I also noticed that the CPU usage sometimes differs from start to start. So this might be something with our simulation setup (which also uses GPU acceleration)

At least with #13 fixed, we can tune the parameters to something workable. :+1:

**Comment by mktk1117** [comment]
Great! I will then merge this into main.
