### ISSUE TITLE
Traversability jumping when update_pose_fps is not 10 Hz

### ISSUE THREAD

**Issue by AlexReimann** [leggedrobotics/elevation_mapping_cupy#13]
The traversability data seems to be jumping around when the `update_pose_fps` is not 10 Hz.

Following was recorded with `update_pose_fps: 1.0`:
![gpu_mapping_jumps](https://user-images.githubusercontent.com/7090417/167846760-c4050113-8dd1-47d9-ab64-9ec64bfa9322.gif)

The blue area is not jumping with 10 Hz. It is also jumping with e. g. 13 Hz.

I tested it on the latest main with the turtlebot sim launcher

**Comment by lorenwel** [comment]
As mentioned in #12, please check if the `fix/improve_shifting` branch fixes this.

**Comment by AlexReimann** [comment]
`fix/improve_shifting` indeed fixes this

**Comment by mktk1117** [comment]
Opened PR #14 for this.
