### ISSUE TITLE
Install not working because of missing python module setup

### ISSUE THREAD

**Issue by AlexReimann** [leggedrobotics/elevation_mapping_cupy#16]
Building the package with the catkin install option (to e.g. make a debian package) does not result in a usable package.

Several things are missing:
* Install for config and launch folder
* Adding install for python (CMakeList and maybe `setup.py`
* Python modules arrangement (missing `__init__.py`, qualifiers)

I started making a PR to fix this, but I'm not sure what layout you want for the python modules.

Any preferences? Do you want / plan to fix this yourselves?

**Comment by mktk1117** [comment]
Hi Alex, thank you for your suggestion!
If the layout makes sense, it is fine. 
Looking forward to seeing your PR :)
