### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by alexMarFar** [leggedrobotics/elevation_mapping_cupy#21]
Hi! I had been using the elevation_mapping version and it was working just fine, so I decided to upgrade to this cupy version. 

Unfortunately, it does not seem to be working properly anymore, the publications and subscriptions seem okay, but the published topics return NaN values. I am wondering whether there is a frame issue or something else? 

In general, what modifications need to be done from one elevation_mapping version to the other? Thank you in advance! :)

**Comment by mktk1117** [comment]
Hello!
Did you get any warning message? 
If it is a frame issue you should have seen some warning messages.

**Comment by alexMarFar** [comment]
Hi! It was a problem with missing tfs indeed on my part. It is now solved, thank you!
