### ISSUE TITLE
error about cupy

### ISSUE THREAD

**Issue by pengpengfei97** [leggedrobotics/elevation_mapping_cupy#22]
Hi,thanks for your excellent work!
There is something wrong when I run the Basic usage. After I built the package and entered `roslaunch elevation_mapping_cupy elevation_mapping_cupy.launch` in the terminal, I got this error :
```
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ModuleNotFoundError: No module named 'cupy'

At:
  /home/intel-nuc/ros_workspace/elevation_mapping_cupy_ws/src/elevation_mapping_cupy/elevation_mapping_cupy/script/elevation_mapping_cupy/traversability_filter.py(5): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  /home/intel-nuc/ros_workspace/elevation_mapping_cupy_ws/src/elevation_mapping_cupy/elevation_mapping_cupy/script/elevation_mapping_cupy/elevation_mapping.py(10): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
```
It looks like that I don't install cupy, then I install it with my cuda version, but the error still exists.
I'm wondering if it's because of conda？So do you know how to fix it? Thanks!

**Comment by pengpengfei97** [comment]
Solved, it is caused by anaconda.

**Comment by alexMarFar** [comment]
Hi! I'm having the same problem, apparently CUDA 11.4 is no longer employed and using 11.3 or 11.6 gives me the same problem. Can you please let me know how did you fix it?


terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
================================================================


At:
  /home/username/.local/lib/python3.8/site-packages/cupy/__init__.py(20): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  /home/username/catkin_ws/src/elevation_mapping_cupy/elevation_mapping_cupy/script/elevation_mapping_cupy/traversability_filter.py(5): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  /home/username/catkin_ws/src/elevation_mapping_cupy/elevation_mapping_cupy/script/elevation_mapping_cupy/elevation_mapping.py(10): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load

**Comment by mmattamala** [comment]
I've been using the elevation mapping package with CUDA 10.2, 11.4 and 11.6 and it works as long as the versions match, so there could be a problem there.

- Which driver you have installed? 
- Is CuPy exactly matching that version? 
- How did you install CuPy too?
- If you open a terminal with Python and import CuPy you get the same error?

**Comment by P1terQ** [comment]
The trigger may be that the python program can't find your dist-packages. My solution is adding `export PYTHONPATH=/home/icr/.local/lib/python3.8/site-packages:$PYTHONPATH` to .bashrc
