### ISSUE TITLE
Can't visualize the planar region type message in rviz

### ISSUE THREAD

**Issue by ArghyaChatterjee** [leggedrobotics/elevation_mapping_cupy#34]
Hi , I am not sure if there is a separate plugin in rviz to show the `convex_plane_decomposition_msgs/PlanarRegion[] planarRegions` type message. I can't visualize the message for some reason inside rviz.

**Comment by rubengrandia** [comment]
This message does not have an RViz visualization plugin and is there to send the full terrain representation to other nodes. The boundaries of the regions can be visualized via the "boundaries" topic. 

As you see here, they are extracted from the full representation just for visualization:
https://github.com/leggedrobotics/elevation_mapping_cupy/blob/da20a703ba892ed9a2411956bf7f9116fb98b034/plane_segmentation/convex_plane_decomposition_ros/src/ConvexPlaneDecompositionRos.cpp#L156
