### ISSUE TITLE
Segmentation fault on ubuntu18.04 melodic x86_64 PC

### ISSUE THREAD

**Issue by JACKLiuDay** [leggedrobotics/elevation_mapping_cupy#35]
Hi, thank you for your guys great work. I am trying to build ele project on my laptop, which is x86_64 ubuntu 18.04 melodic. I built the dependencies such as cuda, cudnn and so on. My cuda is 10.2.89, cudnn 8.6.0. But when I run ele, it shows segmentation fault. Can you guys give me some help.  Some packages are installed with wrong version？
![image](https://user-images.githubusercontent.com/30967867/198237634-58446c18-ea39-4593-a55b-49b1158e1560.png)

**Comment by JACKLiuDay** [comment]
![image](https://user-images.githubusercontent.com/30967867/198919856-84e17993-a117-43bc-b22f-640ce1acb7a4.png)
I wrote a script to test where is the segmentation fault position. The script can import these modules successfully. But in the elecation_cupy, it will report seg fault. 
![image](https://user-images.githubusercontent.com/30967867/198920048-eb5b834e-c1df-42ca-b72e-61b58887b815.png)
It looks like something wrong with elevation_mapping.py. Hope you guys give me some advices.

**Comment by mktk1117** [comment]
Thanks for the report.
Does this also happen if you just run elevation_mapping.py?

**Comment by JACKLiuDay** [comment]
> Thanks for the report. Does this also happen if you just run elevation_mapping.py?

![image](https://user-images.githubusercontent.com/30967867/200117336-3ac35e0f-deaa-4a78-a8bf-adc9f7e6afb5.png)
Hi, thank you so much for your reply. I tired to just run elevation_mapping.py. It shows some errors in the figure. I tried to build this porject on another laptop with ubuntu20.04 ros noetic. And it works perfectly. My cuda is 11.6, cupy 116 now. I am wondering maybe something wrong with melodic, because it works with python2.7. In 20.04, ros works with python3.8?

**Comment by JACKLiuDay** [comment]
I have installed this project on ubuntu 20.04 successfully. Now it works perfectly.

**Comment by martinlucan** [comment]
> I have installed this project on ubuntu 20.04 successfully. Now it works perfectly.

Hey @JACKLiuDay , have you managed to run it on Ubuntu 18.04 and ROS Melodic? I face the same issue.

**Comment by JACKLiuDay** [comment]
> > I have installed this project on ubuntu 20.04 successfully. Now it works perfectly.
> 
> Hey @JACKLiuDay , have you managed to run it on Ubuntu 18.04 and ROS Melodic? I face the same issue.

Hey, I tried this project on ubuntu 18.04. But the program has some segmentation fault. So I abandoned using elevation on 18.04.
