### ISSUE TITLE
Any paper associated with the work

### ISSUE THREAD

**Issue by ArghyaChatterjee** [leggedrobotics/elevation_mapping_cupy#36]
Hello, I was wondering if you have published any paper associated with this repo (or work) to better understand the overall architecture and your implementation. Thanks in advance.

**Comment by lorenwel** [comment]
Hi. 
As linked in the Readme, you can find the corresponding paper [on arXiv](https://arxiv.org/abs/2204.12876).
It was accepted to IROS this year and will eventually also be available through IEEE.
