### ISSUE TITLE
Recreating elevation mapping track_point_x, track_point_y functionality

### ISSUE THREAD

**Issue by gibinjoe** [leggedrobotics/elevation_mapping_cupy#42]
In my usage of elevation mapping (CPU) package, I mainly need the terrain in front of the robot.  Hence, I used the track_point_x parameter to offset the robot from being the center of the map.  Is it possible to do the same in elevation_mapping_cupy package?  I dont see any such parameters in the parameters.yaml file.  Thank you.

**Comment by lorenwel** [comment]
The parameter you're looking for is the `base_frame` parameter. It uses this TF frame to determine the robot position, and therefore the map origin. 
You can offset the map center by publishing a TF which is offset from your base:
`rosrun tf2_ros static_transform_publisher 1.0 0 0 0 0 0 base base_offset` will keep the map centered one meter in front of the robot for example. Assuming that the `base` frame is the center of your robot.
