### ISSUE TITLE
Custom Kernel Update Question

### ISSUE THREAD

**Issue by Kennard123661** [leggedrobotics/elevation_mapping_cupy#56]
Hi!

Thanks for your work. For this function in custom_kernels.py:
![image](https://github.com/leggedrobotics/elevation_mapping_cupy/assets/17818981/1e63fbda-d1dc-4ed6-b9f3-6c09bdbd25c3)

For lines 171-172, it seems to read from map, but lines 187-193 seems to perform non-atomic updates to map which could cause 171-172 to use different values depending on the thread order on the CUDA kernel. Would this happen? 

It seems like this does not happen on from the visualizations but I was wondering if this is a potential issue because I am planning to use the code for further research...

Thank you!

**Comment by mktk1117** [comment]
Thanks for the comments! As far as we tested on the robot it was not causing any issues.
