### ISSUE TITLE
cupy.int Problem

### ISSUE THREAD

**Issue by CihatAltiparmak** [leggedrobotics/elevation_mapping_cupy#57]
Hello, 
Firstly, i want to thank you for your work. I am trying to use `elevation_mapping_cupy` on nvidia agx orin with ros-noetic for the quadruped robot. I installed `cupy` module by running `pip3 install cupy`. But i have experienced that `AttributeError: module 'cupy' has no attribute 'int'`. So i started to search this error and i found that there are `cupy.int8 cupy.int16 cupy.int32 cupy.int64 cupy.int_` in cupy module but i haven't seen `cupy.int`. Maybe it's possible that there exists `cupy.int` in previous versions of cupy module. For all that, i should say that i haven't been able to found that version. Therefore i decided to open pr for this problem if you are interested in. I am sorry for me to be unable to share helpful ss for you now. I will add this informations ,how  i have installed `cuda` `cudnn`, `opencv`, `pytorch` and which cupy version i use etc., asap. 

Thank you in advance.

**Comment by mktk1117** [comment]
Thanks for your Pull Request! Yeah maybe they changed with the new version similar to numpy.
