### ISSUE TITLE
Traversability Filter

### ISSUE THREAD

**Issue by Hussain7252** [leggedrobotics/elevation_mapping_cupy#70]
Can someone please guide me towards the papers that provide insights on how the elevation map of terrains were used to generate data and to train the CNN in order to provide traversability estimates.

**Comment by mktk1117** [comment]
In this paper the CNN training part is explained. Please have a look.
https://ieeexplore.ieee.org/abstract/document/9636358

**Comment by Hussain7252** [comment]
Thanks alot
