### ISSUE TITLE
Installation issues - Unable to find libcudart.so.11.0 

### ISSUE THREAD

**Issue by IoannisDadiotis** [leggedrobotics/elevation_mapping_cupy#77]
I am facing some issues installing the library on ubuntu 20.04. `nvidia-smi` on my system indicates CUDA VERSION 11.4
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T600         Off  | 00000000:01:00.0 Off |                  N/A |
| 43%   52C    P5    N/A /  41W |    644MiB /  3911MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1563      G   /usr/lib/xorg/Xorg                126MiB |
|    0   N/A  N/A      2310      G   /usr/lib/xorg/Xorg                227MiB |
|    0   N/A  N/A      2485      G   /usr/bin/gnome-shell               65MiB |
|    0   N/A  N/A      4179      G   ...AAAAAAAAA= --shared-files       33MiB |
|    0   N/A  N/A      4208      G   /usr/lib/firefox/firefox          181MiB |
+-----------------------------------------------------------------------------+
```
First regarding downloading cuDNN I tried downloaded  file `cudnn-local-repo-ubuntu2004-8.9.7.29_1.0-1_amd64.deb` from https://developer.nvidia.com/rdp/cudnn-download. Then I followed the debian local installation guide [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-deb). The problem was that when running
```
sudo apt-get install libcudnn8=8.9.7.29-1+cuda11.4
sudo apt-get install libcudnn8-dev=8.9.7.29-1+cuda11.4        
```
gave me 
`E: Version '8.9.7.29-1+cuda11.4' for 'libcudnn8' was not found` and the only way to run this was with `*cuda11.8` which makes me think that is wrong due to cuda 11.4 on my system.

Despite this I completed the installation guide you have in your documentation and built the packages.
When I run `roslaunch elevation_mapping_cupy elevation_mapping_cupy.launch` I get the error:
```
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
================================================================
```
When I run `locate libcudart.so` I get:
```
/home/idadiotis/.local/lib/python3.8/site-packages/nvidia/cuda_runtime/lib/libcudart.so.12
/usr/local/MATLAB/R2022a/bin/glnxa64/libcudart.so.11.0
/usr/local/MATLAB/R2022a/bin/glnxa64/libcudart.so.11.2.152
```
Any idea how to fix the installation?
Thank you in advance for any help.

**Comment by mktk1117** [comment]
Also can you double check which cupy you have installed?

**Comment by IoannisDadiotis** [comment]
> Also can you double check which cupy you have installed?

I did `pip3 install cupy-cuda114`. I can see folders cupy, cupy_backends, cupy_cuda114-10.6.0.dist-info and cupyx in my `~/.local/lib/python3.8/site-packages`.

**Comment by mktk1117** [comment]
umm, the cupy version looks correct. 
Does it happen when you just run python and then import cupy? or it only happens when you run with ros?

**Comment by IoannisDadiotis** [comment]
It happens also on python.

To me it is quite strange that I have the following files in my system
```
/home/idadiotis/.local/lib/python3.8/site-packages/nvidia/cuda_runtime/lib/libcudart.so.12
/usr/local/MATLAB/R2022a/bin/glnxa64/libcudart.so.11.0
/usr/local/MATLAB/R2022a/bin/glnxa64/libcudart.so.11.2.152
```
The executable is looking for `*.so.11` while I have `*.so.12` installed. There is a library with `*.so.11.0` under the MATLAB folder but I guess these (should) have nothing to do with the installation of elevation_mapping_cupy, right?

**Comment by IoannisDadiotis** [comment]
I am giving a try through the docker container but I am facing some issues also this way. See below:
```
$ ./build.sh 
[+] Building 1.3s (13/17)                                                                                                                                                                           docker:default
 => [internal] load build definition from Dockerfile.x64                                                                                                                                                      0.0s
 => => transferring dockerfile: 1.61kB                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04                                                                                                                        0.5s
 => [ 1/13] FROM docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04@sha256:72d9b042337ea385b36d40638e8cbe1968f098773be49493ccef8b95f069711d                                                                0.0s
 => [internal] load build context                                                                                                                                                                             0.0s
 => => transferring context: 38B                                                                                                                                                                              0.0s
 => CACHED [ 2/13] RUN echo "Etc/UTC" > /etc/timezone &&     ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime &&     apt-get update && apt-get install -y tzdata &&     dpkg-reconfigure --frontend noninte  0.0s
 => CACHED [ 3/13] RUN apt-get update && apt-get install -y     python3.8     python3-pip     git                                                                                                             0.0s
 => CACHED [ 4/13] RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118                                                                                           0.0s
 => CACHED [ 5/13] COPY requirements.txt /tmp/requirements.txt                                                                                                                                                0.0s
 => CACHED [ 6/13] RUN pip3 install -r /tmp/requirements.txt                                                                                                                                                  0.0s
 => CACHED [ 7/13] RUN pip3 install cupy-cuda11x scikit-learn                                                                                                                                                 0.0s
 => CACHED [ 8/13] RUN pip3 install 'git+https://github.com/facebookresearch/detectron2.git'                                                                                                                  0.0s
 => ERROR [ 9/13] RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654                                                                             0.7s
------                                                                                                                                                                                                             
 > [ 9/13] RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654:                                                                                        
0.299 Warning: apt-key output should not be parsed (stdout is not a terminal)                                                                                                                                      
0.343 Executing: /tmp/apt-key-gpghome.wl5kZCtONQ/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654                                                            
0.583 gpg: CRC error; 14C720 - 6C9712                                                                                                                                                                              
0.583 gpg: read_block: read error: Invalid keyring
0.583 gpg: Total number processed: 0
------
Dockerfile.x64:28
--------------------
  26 |     
  27 |     # Install ROS
  28 | >>> RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  29 |     RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
  30 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654" did not complete successfully: exit code: 2
```

**Comment by georgflick** [comment]
```
dpkg -S libcudart.so.11.0```
gives me:
cuda-cudart-11-4: /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0

have you tried to install the `cuda-cudart-11-4` package?
Otherwise you can also install the full cuda package: `cuda-11-4` that should work for sure.

**Comment by mktk1117** [comment]
> I am giving a try through the docker container but I am facing some issues also this way. See below:
> 
> ```
> $ ./build.sh 
> [+] Building 1.3s (13/17)                                                                                                                                                                           docker:default
>  => [internal] load build definition from Dockerfile.x64                                                                                                                                                      0.0s
>  => => transferring dockerfile: 1.61kB                                                                                                                                                                        0.0s
>  => [internal] load .dockerignore                                                                                                                                                                             0.0s
>  => => transferring context: 2B                                                                                                                                                                               0.0s
>  => [internal] load metadata for docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04                                                                                                                        0.5s
>  => [ 1/13] FROM docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04@sha256:72d9b042337ea385b36d40638e8cbe1968f098773be49493ccef8b95f069711d                                                                0.0s
>  => [internal] load build context                                                                                                                                                                             0.0s
>  => => transferring context: 38B                                                                                                                                                                              0.0s
>  => CACHED [ 2/13] RUN echo "Etc/UTC" > /etc/timezone &&     ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime &&     apt-get update && apt-get install -y tzdata &&     dpkg-reconfigure --frontend noninte  0.0s
>  => CACHED [ 3/13] RUN apt-get update && apt-get install -y     python3.8     python3-pip     git                                                                                                             0.0s
>  => CACHED [ 4/13] RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118                                                                                           0.0s
>  => CACHED [ 5/13] COPY requirements.txt /tmp/requirements.txt                                                                                                                                                0.0s
>  => CACHED [ 6/13] RUN pip3 install -r /tmp/requirements.txt                                                                                                                                                  0.0s
>  => CACHED [ 7/13] RUN pip3 install cupy-cuda11x scikit-learn                                                                                                                                                 0.0s
>  => CACHED [ 8/13] RUN pip3 install 'git+https://github.com/facebookresearch/detectron2.git'                                                                                                                  0.0s
>  => ERROR [ 9/13] RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654                                                                             0.7s
> ------                                                                                                                                                                                                             
>  > [ 9/13] RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654:                                                                                        
> 0.299 Warning: apt-key output should not be parsed (stdout is not a terminal)                                                                                                                                      
> 0.343 Executing: /tmp/apt-key-gpghome.wl5kZCtONQ/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654                                                            
> 0.583 gpg: CRC error; 14C720 - 6C9712                                                                                                                                                                              
> 0.583 gpg: read_block: read error: Invalid keyring
> 0.583 gpg: Total number processed: 0
> ------
> Dockerfile.x64:28
> --------------------
>   26 |     
>   27 |     # Install ROS
>   28 | >>> RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
>   29 |     RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
>   30 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654" did not complete successfully: exit code: 2
> ```

Umm, let me check this error soon.
Could you try just pulling the docker image as well?

**Comment by IoannisDadiotis** [comment]
> ```
> dpkg -S libcudart.so.11.0
> ```
> 
> gives me:
> 
> ```
> cuda-cudart-11-4: /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
> ```
> 
> have you tried to install the `cuda-cudart-11-4` package? Otherwise you can also install the full cuda package: `cuda-11-4` that should work for sure.

@georgflick Thanks for the suggestion. Do you remember how did you install `cuda-cudart-11-4` or `cuda-11-4`?

**Comment by IoannisDadiotis** [comment]
> 
> Umm, let me check this error soon. Could you try just pulling the docker image as well?

@mktk1117  I get the following output when I `./run.sh`:
```
$ ./run.sh 
---------------------
[run.sh]: The final run command is
docker run   --volume=/tmp/.X11-unix:/tmp/.X11-unix:rw   --volume=/tmp/.docker.xauth:/tmp/.docker.xauth:rw   --env=QT_X11_NO_MITSHM=1   --env=XAUTHORITY=/tmp/.docker.xauth   --env=DISPLAY=:1   --ulimit rtprio=99   --cap-add=sys_nice   --privileged   --net=host   -eHOST_USERNAME=idadiotis   -v/home/idadiotis:/home/idadiotis   -v/home/idadiotis/elevation_ws/src/elevation_mapping_cupy/docker/.etc/shadow:/etc/shadow   -v/home/idadiotis/elevation_ws/src/elevation_mapping_cupy/docker/.etc/passwd:/etc/passwd   -v/home/idadiotis/elevation_ws/src/elevation_mapping_cupy/docker/.etc/group:/etc/group   -v/media:/media   --gpus all   -it mktk1117/elevation_mapping_cupy:latest.
Unable to find image 'mktk1117/elevation_mapping_cupy:latest' locally
latest: Pulling from mktk1117/elevation_mapping_cupy
7a2c55901189: Pull complete 
a3d20efe6db8: Pull complete 
bfdf8ce43b67: Pull complete 
ad14f66bfcf9: Pull complete 
1056ff735c59: Pull complete 
a08e157987cd: Pull complete 
b05f735a8d36: Pull complete 
2ca2acc6de6f: Pull complete 
a5f96919abbf: Pull complete 
49870781e01a: Pull complete 
75b341fae5a3: Pull complete 
f6aa8af2b323: Pull complete 
6cd6b35592e7: Pull complete 
48c8977a774b: Pull complete 
2901aede192c: Pull complete 
8e53ab202ea2: Pull complete 
03183d9122a5: Pull complete 
cd4db5efad37: Pull complete 
c2fc76707dd9: Pull complete 
c907e17f9cc6: Pull complete 
6e5236eac1ae: Pull complete 
900d81262412: Pull complete 
18d3fe5ae6cc: Pull complete 
59ecd8c97b71: Pull complete 
Digest: sha256:2334b929134883b1b5c5d4b1b1e7820af1f09ecd8edf6e93de38aea5b360d059
Status: Downloaded newer image for mktk1117/elevation_mapping_cupy:latest
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0234] error waiting for container:                 
[run.sh]: Docker terminal closed.
```

**Comment by georgflick** [comment]
> > ```
> > dpkg -S libcudart.so.11.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gives me:
> > ```
> > cuda-cudart-11-4: /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > have you tried to install the `cuda-cudart-11-4` package? Otherwise you can also install the full cuda package: `cuda-11-4` that should work for sure.
> 
> @georgflick Thanks for the suggestion. Do you remember how did you install `cuda-cudart-11-4` or `cuda-11-4`?

we are installing cuda that way:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
echo "deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" | sudo tee /etc/apt/sources.list.d/cuda-ubuntu2004-x86_64.list
sudo apt-get update
sudo apt-get install cuda=11.4.4-1
```
and after that you can set cuda to hold to prevent it from updating by:
`sudo apt-mark hold cuda`

**Comment by IoannisDadiotis** [comment]
Before I install other cuda-related stuff I want to make sure I am not messing my system. I am a bit confused about what cuda version is already installed on my system and what should I install. In particular, `nvidia-smi` gives me cuda 11.4 but `nvcc -V` gives me cuda 10.1.243:
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
Also I get:
```
$ whereis cuda
cuda: /usr/lib/cuda /usr/include/cuda.h
$ cat /usr/lib/cuda/version.txt 
CUDA Version 10.1.243
```

**Comment by mktk1117** [comment]
Did you install Nvidia docker??

Seems like a install issue with cupy.maybe you can try building cupy by installing just cupy without cuda versions.

pip install cupy

**Comment by IoannisDadiotis** [comment]
> Did you install Nvidia docker??
> 
> Seems like a install issue with cupy.maybe you can try building cupy by installing just cupy without cuda versions.
> 
> pip install cupy

Installing `nvidia-container-toolkit` fixed the docker issue.  From a fast check it seems that now I am able to run the turtlesim examples successfully.

Btw I think there is a small typo in the launch file below:
https://github.com/leggedrobotics/elevation_mapping_cupy/blob/6ad593642715c342f16d27e9251b84c356efe370/elevation_mapping_cupy/launch/turtlesim_plane_decomposition_example.launch#L6
I guess it should be `turtlesim_simple_example.launch` instead of `turtlesim_example.launch`.
