### ISSUE TITLE
pybind11 problem

### ISSUE THREAD

**Issue by niteofhunter** [leggedrobotics/elevation_mapping_cupy#83]
Hi.

I got the pybind error in "roslaunch elevation_mapping_cupy turtlesim_simple_example.launch"

![image](https://github.com/leggedrobotics/elevation_mapping_cupy/assets/10339608/97f081ab-95f2-4308-b8ac-e167060e4753)

But simple-parsing was already installed.

Could you tell me how to fix it??????

Thank you ^^

ROS_VERSION : noetic(20.04)

p.s. it works well in melodic(18.04)

**Comment by mktk1117** [comment]
Could you check which python you're using for ros and check if you can import using that python version?
Maybe you have installed in python2 so it worked with melodic, but not working with noetic since it uses python3.

**Comment by niteofhunter** [comment]
> Could you check which python you're using for ros and check if you can import using that python version? Maybe you have installed in python2 so it worked with melodic, but not working with noetic since it uses python3.

Thank you for your answer^^

It works well when I use pybind11 instead of pybind11_catkin.

**Comment by mktk1117** [comment]
Great!
