### ISSUE TITLE
Jetson NX , [elevation_mapping-2] process has died [pid 13347, exit code -11

### ISSUE THREAD

**Issue by hangtianxia** [leggedrobotics/elevation_mapping_cupy#92]
I'm encountering an issue where the process terminates unexpectedly on Jetson NX when calling map_.initialize(nh_) in the elevation_mapping_ros.cpp file. The error message "process has died" appears, indicating a problem with the initialization process.
<img width="488" alt="截屏2024-04-09 20 22 23" src="https://github.com/leggedrobotics/elevation_mapping_cupy/assets/31307562/e40ab9b3-75aa-4721-815e-9d197aa7bada">
<img width="904" alt="截屏2024-04-09 20 27 47" src="https://github.com/leggedrobotics/elevation_mapping_cupy/assets/31307562/ce53fbb2-0c1f-4b18-a5c1-00d6f608db41">
![c15ece56318f557e9bb618845756d314](https://github.com/leggedrobotics/elevation_mapping_cupy/assets/31307562/9cb72703-f9c2-43f7-aa52-7564b17c4241)
![cdcace58d4c4534518e43e855ef54fbd](https://github.com/leggedrobotics/elevation_mapping_cupy/assets/31307562/53c4b5d5-98de-4c78-9afc-957cca91c9dd)

Additional information:
· ROS version: Melodic
· Ubuntu version: 18.04
· CUDA version: 10.2

**Comment by MyDearestJingo** [comment]
Could u use GDB or another debug tool to find where it stopped at?

**Comment by hangtianxia** [comment]
> Could u use GDB or another debug tool to find where it stopped at?

It stopped at `auto elevation_mapping = py::module::import("elevation_mapping_cupy.elevation_mapping");,`  and it seems that it didn't successfully import elevation_mapping.py.

**Comment by mktk1117** [comment]
It might be because of python path.
Did you try doing this?

https://leggedrobotics.github.io/elevation_mapping_cupy/getting_started/tutorial.html#errors

**Comment by hangtianxia** [comment]
I tred, but it's not very useful.

**Comment by mktk1117** [comment]
umm, then you might be missing some python dependency.
Could you double check if you have installed all packages?
